display_errors=Off
log_errors=On
error_reporting=E_ALL
memory_limit=256M
upload_max_filesize=128M
post_max_size=128M
max_execution_time=300
max_input_time=300
date.timezone=Asia/Shanghai
session.save_path=/tmp
